version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0.30
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_clinica
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    links:
      - mysql
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - mynetwork

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - mynetwork

  vue:
    image: node:latest
    container_name: vue
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./vite-project:/app
    command: npm run dev
    ports:
      - 8082:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
